**np.linspace()**

In [1]:
# to will like a space
# ot will generate only specificed number  in a specific range
# range( start   stop )
# how many numbers i need to display

In [56]:
import numpy as np
np.linspace(1,100,10)  # start=1 stop=100 size=10
# from 1 to 100 it will give 10 numbers with equal space

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [5]:
np.linspace(1,100,4)
# start=1 stop=100 size=4
# from 1 to 100 it will give 4 numbers

array([  1.,  34.,  67., 100.])

In [50]:
np.linspace(start=1,stop=50,num=4)

array([ 1.        , 17.33333333, 33.66666667, 50.        ])

### **np.zeros()**

In [ ]:
# suppose i want to make all zeroes 

In [7]:
np.zeros(10)
# 1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [11]:
np.zeros((3,3)) # shape # 2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [53]:
np.zeros((2,3,3)) # 3d create a 3 dimension matrix with zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
np.zeros((4,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [60]:
np.zeros((4,2),dtype=bool)

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [61]:
np.zeros((4,2),dtype=str)

array([['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

## **np.ones()**

In [8]:
np.ones(10)
# 1d # created a matrix having 10 elements all are ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [54]:
np.ones((4,2),dtype=int) # shape

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [55]:
np.ones((4,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
np.ones((4,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [57]:
np.ones((4,2),dtype=bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

#### writing shape is not compulsory

In [55]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


## **np.empty**

- it will generate random matrix with given shape and data type

In [18]:
np.empty(shape=(2,2))  # default float output is coming

array([[1., 1.],
       [1., 1.]])

In [21]:
np.empty(shape=(2,2),dtype=float)

array([[1., 1.],
       [1., 1.]])

In [19]:
np.empty(shape=(3,3),dtype=int)

array([[-603036432,        411,  537552242],
       [1830821920, 1769173865, 1763731310],
       [1768235118, 1919248500,  543584032]])

In [22]:
np.empty(shape=(3,3)) # float dtype give default

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.empty(shape=(3,3),dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [27]:
np.empty(shape=(3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
# why 1 is taking every time in values

In [30]:
np.empty(shape=(2,2),dtype=int,order="2" )

ValueError: order must be one of 'C', 'F', 'A', or 'K' (got '2')

In [33]:
np.empty(shape=(2,2),dtype=int,order="F" )

array([[-742039941, 1530249597],
       [-720028240, 1836691400]])

In [34]:
np.empty(shape=(2,2),dtype=int,order="A" )

ValueError: only 'C' or 'F' order is permitted

In [38]:
np.empty(shape=(2,2),dtype=int,order="C",like="44" )

TypeError: The `like` argument must be an array-like that implements the `__array_function__` protocol.

**np.full()**

- it will also return matrix with some fills

In [40]:
np.full((3,3),fill_value=100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [41]:
np.full((3,3),50)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [68]:
np.full((3,3),fill_value=(1,2))

ValueError: could not broadcast input array from shape (2,) into shape (3,3)

In [45]:
np.full((3,3),[1,2])

ValueError: could not broadcast input array from shape (2,) into shape (3,3)

In [61]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

In [62]:
np.full((2, 2,3), [1, 2,3])

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

## **np.identity()**

In [46]:
np.identity(3) # give a 3*3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.identity(5) # give a 5*5 matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# we can create array using tuple or list np.array[(1,2)] or np.array[[1,2]] both are same

In [70]:
np.identity(3,dtype=str)

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

In [72]:
np.identity(3,dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [73]:
np.identity(3,fill_value=5)

TypeError: identity() got an unexpected keyword argument 'fill_value'

## np.eye()

In [ ]:
# N*M matrix
# 4*5 matrix
# k>0 represent upper diagonal
# k<0 represent lower diagonal
# if n=m and k=0 identity matrix created

In [74]:
np.eye(4,5) # default k=0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [77]:
np.eye(5,5,k=0) # default k=0 
# means 1 values start first column first row then so on identity
# if k=2 then values(1) start from 2nd column of first row then so on identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
np.eye(4,5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
np.eye(4,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [79]:
np.eye(4,5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
np.eye(4,5,k=4)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
np.eye(4,5,k=5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.eye(4,5,k=6)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
np.eye(4,5,k=100)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
np.eye(4,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [85]:
np.eye(4,5,k=-0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [86]:
np.eye(4,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [87]:
np.eye(4,5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [88]:
np.eye(4,5,k=-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [89]:
np.eye(4,5,k=-100)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
np.eye(3,3) # k=0 default # identity matrix has been created

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.eye(3,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [92]:
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [93]:
np.eye(3,3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [94]:
np.eye(3,3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
np.eye(3,3,k=40000)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.linspace()
np.ones()
np.zeros()
np.full()
np.empty()
np.eye()

## reshape()

In [ ]:
# numpy array has shape(3,2)  3*2=6
# reshape into (6,1)
# possible ways (1,6) (2,3) (3,2) (6,1)

In [64]:
employee=np.array([('ram',18),('lakshan',19),('krishna',22)]) # use tuple or list inside 
employee

array([['ram', '18'],
       ['lakshan', '19'],
       ['krishna', '22']], dtype='<U11')

In [100]:
employee.shape

(3, 2)

In [101]:
employee.reshape(1,6) # 1 row 6 columns

array([['ram', '18', 'lakshan', '19', 'krishna', '22']], dtype='<U11')

In [102]:
employee.reshape(6,1)

array([['ram'],
       ['18'],
       ['lakshan'],
       ['19'],
       ['krishna'],
       ['22']], dtype='<U11')

In [103]:
employee.reshape(2,3)

array([['ram', '18', 'lakshan'],
       ['19', 'krishna', '22']], dtype='<U11')

In [104]:
employee.reshape(4,4)

ValueError: cannot reshape array of size 6 into shape (4,4)

## indexing

In [65]:
employee

array([['ram', '18'],
       ['lakshan', '19'],
       ['krishna', '22']], dtype='<U11')

In [106]:
employee[0] # index first list 

array(['ram', '18'], dtype='<U11')

In [107]:
employee[1] # index of second list

array(['lakshan', '19'], dtype='<U11')

In [108]:
employee[2] # index of third list

array(['krishna', '22'], dtype='<U11')

In [109]:
employee[0][0] # index of first list in first column

'ram'

In [110]:
employee[0][1]

'18'

In [111]:
employee[2][0]

'krishna'

In [112]:
employee[2][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [69]:
employee[1,1]

'19'

In [ ]:
employee[rows,colummn]

## slicing

In [113]:
arr1=np.array([73,56,89,90,95,72,84,94,74,37])
arr1    # 1d

array([73, 56, 89, 90, 95, 72, 84, 94, 74, 37])

In [114]:
arr1[3]

90

In [115]:
arr1[3:5]

array([90, 95])

In [116]:
arr1[::-1]

array([37, 74, 94, 84, 72, 95, 90, 89, 56, 73])

In [117]:
employee # 2d

array([['ram', '18'],
       ['lakshan', '19'],
       ['krishna', '22']], dtype='<U11')

In [118]:
employee[0:2]

array([['ram', '18'],
       ['lakshan', '19']], dtype='<U11')

In [119]:
employee[0][0:2]

array(['ram', '18'], dtype='<U11')

In [120]:
employee[0][::-1]

array(['18', 'ram'], dtype='<U11')

In [121]:
employee[2][::-1]

array(['22', 'krishna'], dtype='<U11')

In [122]:
arr1

array([73, 56, 89, 90, 95, 72, 84, 94, 74, 37])

In [123]:
arr1[::2] # step=2

array([73, 89, 95, 84, 74])

In [124]:
arr1[::-2] # step=-2

array([37, 94, 72, 90, 56])

In [125]:
employee

array([['ram', '18'],
       ['lakshan', '19'],
       ['krishna', '22']], dtype='<U11')

In [126]:
# can be done by putting comma

In [127]:
employee[0,0] # first zero represent first list # second zero represent first column

'ram'

In [129]:
employee[0,0:2]

array(['ram', '18'], dtype='<U11')

In [130]:
employee[0,::-1]

array(['18', 'ram'], dtype='<U11')

In [131]:
employee[0:2,0:2]

array([['ram', '18'],
       ['lakshan', '19']], dtype='<U11')

In [132]:
employee[0:2][0:2] # same as above

array([['ram', '18'],
       ['lakshan', '19']], dtype='<U11')

In [134]:
employee[0:3,0]

array(['ram', 'lakshan', 'krishna'], dtype='<U11')

In [135]:
employee[0:3,1]

array(['18', '19', '22'], dtype='<U11')

In [143]:
employee[2:0,1]

array([], dtype='<U11')

# array operation

In [144]:
odd_num=np.array([1,3,5,7,9])
even_num=np.array([2,4,6,8])   # remember no. of elements are must be same 
print("old num ",odd_num)
print("even num ",even_num)
print("new num ",odd_num+even_num)


old num  [1 3 5 7 9]
even num  [2 4 6 8]


ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [145]:
odd_num=np.array([1,3,5,7,9])
even_num=np.array([2,4,6,8,10])   # remember no. of elements are must be same 
print("old num ",odd_num)
print("even num ",even_num)
print("new num ",odd_num+even_num)


old num  [1 3 5 7 9]
even num  [ 2  4  6  8 10]
new num  [ 3  7 11 15 19]


In [146]:
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]
# array sum is new num  [ 3  7 11 15 19]
list1+list2 # but list will append numbers not add corresponding elements 
# in order to add 
# for i,j in zip(list1,list2)
#     print(i+j)

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

**arithmetic operation**

In [1]:
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]
list1*list2

TypeError: can't multiply sequence by non-int of type 'list'

In [2]:
list1*2 # list1 + list1

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]

In [5]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [6]:
arr1*2 # arr1([1*2,2*2,3*2]) # see the difference in list and array

array([2, 4, 6])

In [51]:
arr2=np.array([1,2,3])
arr2

array([1, 2, 3])

In [9]:
arr1

array([1, 2, 3])

In [10]:
arr1+arr2 # add corresponding values

array([2, 4, 6])

In [11]:
arr1*arr2 # multpily corresponding values

array([1, 4, 9])

In [12]:
arr1-arr2  # subtracting corresponding values

array([0, 0, 0])

In [13]:
arr1/arr2  # dividing corresponding values 

array([1., 1., 1.])

**Matrix multiplication**

In [14]:
m1=np.array([[1,2,4],[0,-6,3]])
m2=np.array([[0,4,1],[9,5,-1]])
m1,m2 # m1 order 2*3
      # m2 order 2*3

(array([[ 1,  2,  4],
        [ 0, -6,  3]]),
 array([[ 0,  4,  1],
        [ 9,  5, -1]]))

In [15]:
m1+m2 # correponding values are add

array([[ 1,  6,  5],
       [ 9, -1,  2]])

In [16]:
m1*m2 # corresponding values are multiply
# new order is same as m1,m2 2*3 

# element wise product
# hadmard product

array([[  0,   8,   4],
       [  0, -30,  -3]])

In [ ]:
# but i want to matrix multiplication 
# m1.shape 2*3    # m2.shape 2*3
# how can i do matrix multiplication
# do this a*b and c*d order must be same b=c
# new order of matrix is a*d

In [17]:
m1=np.array([[1,2,4],[0,-6,3]]) # 2*3
m2=np.array([[0,4,1],[9,5,-1],[8,4,2]])  # 3*3 

In [18]:
m1.shape

(2, 3)

In [19]:
m2.shape

(3, 3)

In [20]:
m1,m2

(array([[ 1,  2,  4],
        [ 0, -6,  3]]),
 array([[ 0,  4,  1],
        [ 9,  5, -1],
        [ 8,  4,  2]]))

In [21]:
m1*m2 # yess 

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [22]:
m1.dot(m2) # this is the matrix multiplication

array([[ 50,  30,   7],
       [-30, -18,  12]])

**np.square**

- return square of the elements

In [23]:
arr1=np.array([100,200,300,400,500])
np.square(arr1)

array([ 10000,  40000,  90000, 160000, 250000], dtype=int32)

**np.sqrt**

In [24]:
arr1

array([100, 200, 300, 400, 500])

In [25]:
np.sqrt(arr1)
# square root 

array([10.        , 14.14213562, 17.32050808, 20.        , 22.36067977])

**np.power**

In [26]:
arr1

array([100, 200, 300, 400, 500])

In [27]:
np.power(arr1,1)

array([100, 200, 300, 400, 500], dtype=int32)

In [28]:
np.power(arr1,2)

array([ 10000,  40000,  90000, 160000, 250000], dtype=int32)

In [29]:
np.power(arr1,3)

array([  1000000,   8000000,  27000000,  64000000, 125000000], dtype=int32)

In [30]:
np.power(arr1,0.5)
# square root 0.5=1/2

array([10.        , 14.14213562, 17.32050808, 20.        , 22.36067977])

In [35]:
np.power(arr1,-0.5) # -1/2 power 1/arr1 of power -1/2

array([0.1       , 0.07071068, 0.05773503, 0.05      , 0.04472136])

In [33]:
np.power(arr1,-1) # values below zero not take 

ValueError: Integers to negative integer powers are not allowed.

In [36]:
np.power(arr1,-0.2)

array([0.39810717, 0.34657242, 0.31957717, 0.30170882, 0.28853998])

**np.transpose**

In [37]:
m1

array([[ 1,  2,  4],
       [ 0, -6,  3]])

In [38]:
m1.shape

(2, 3)

In [39]:
np.transpose(m1)

array([[ 1,  0],
       [ 2, -6],
       [ 4,  3]])

In [40]:
np.transpose(m1).shape

(3, 2)

In [41]:
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]
list1+list2      # concatenation

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

In [42]:
arr1

array([100, 200, 300, 400, 500])

In [50]:
arr2

array([ 1, 60, 49, 30, 22])

In [44]:
arr1+arr2  
# order must be same while adding 

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [47]:
arr3=np.array([1,60,49,30,22])
arr3

array([ 1, 60, 49, 30, 22])

In [48]:
arr1+arr3 # addition 

array([101, 260, 349, 430, 522])

In [52]:
arr2

array([1, 2, 3])

**np.concatenate**

In [53]:
new_array=np.concatenate([arr1,arr2])
new_array # concatenation

# 1d 

array([100, 200, 300, 400, 500,   1,   2,   3])