**matrix multiplication**

In [4]:
arr1=np.array([[1,2,3],[5,6,7]])
arr2=np.array([[5,0,2],[0,1,2]])

In [2]:
import numpy as np

In [6]:
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [7]:
arr2

array([[5, 0, 2],
       [0, 1, 2]])

In [8]:
arr1.shape

(2, 3)

In [9]:
arr2.shape

(2, 3)

In [10]:
arr1*arr2

array([[ 5,  0,  6],
       [ 0,  6, 14]])

In [11]:
m1=np.array([[1,2,0],[5,0,1]])
m1.shape

(2, 3)

In [12]:
m2=np.array([[1,3],[4,1],[5,9]])
m2.shape

(3, 2)

In [13]:
m1.dot(m2)

array([[ 9,  5],
       [10, 24]])

**np.square()**

In [15]:
arr1=np.array([10,20,30,40])
arr2=np.square(arr1)
arr2

array([ 100,  400,  900, 1600], dtype=int32)

In [16]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [17]:
np.power(arr1,2)

array([ 100,  400,  900, 1600], dtype=int32)

In [18]:
np.power(arr1,3)

array([ 1000,  8000, 27000, 64000], dtype=int32)

In [19]:
np.power(arr2,4)

array([  100000000,  -169803776, -1029996288,  -520093696], dtype=int32)

In [20]:
np.power(arr2,0.5)

array([10., 20., 30., 40.])

**np.transpose**

In [21]:
m1=np.array([(1,2,3),(2,4,1)])
m1.shape

(2, 3)

In [23]:
np.transpose(m1)

(3, 2)

In [24]:
np.transpose(m1).shape

(3, 2)

**np.concatenate**

In [25]:
new_array=np.concatenate(arr1,arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [27]:
new_array=np.concatenate([arr1,arr2])
new_array # 1d

array([  10,   20,   30,   40,  100,  400,  900, 1600])

In [32]:
# 2d 
names=np.array([("a",1),("b",2),("c",3)])
city=np.array([("hyd","040"),("bengaluru","080")])

In [33]:
names

array([['a', '1'],
       ['b', '2'],
       ['c', '3']], dtype='<U11')

In [34]:
city

array([['hyd', '040'],
       ['bengaluru', '080']], dtype='<U9')

In [35]:
np.concatenate([names,city]) # axis=0 default # rows wise

array([['a', '1'],
       ['b', '2'],
       ['c', '3'],
       ['hyd', '040'],
       ['bengaluru', '080']], dtype='<U11')

In [36]:
np.concatenate([names,city],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [37]:
names=np.array([("a",1),("b",2),("c",3)])
city=np.array([("hyd","040"),("bengaluru","080"),("chennai","098")])
np.concatenate([names,city],axis=1) # axis=1 column wise

array([['a', '1', 'hyd', '040'],
       ['b', '2', 'bengaluru', '080'],
       ['c', '3', 'chennai', '098']], dtype='<U11')

**np.flatten**

- any shape of array converts into single dimension

In [38]:
names

array([['a', '1'],
       ['b', '2'],
       ['c', '3']], dtype='<U11')

In [42]:
array_names=np.ndarray.flatten(names)
# 1d

**iteration**

In [43]:
array_names

array(['a', '1', 'b', '2', 'c', '3'], dtype='<U11')

In [44]:
list1=[i for i in array_names]
list1

# iterating array elements using loop

['a', '1', 'b', '2', 'c', '3']

In [45]:
array_names.tolist()  # converting array into list

['a', '1', 'b', '2', 'c', '3']

- numpy operation are faster than list

In [48]:
# list operation
import time
size=10000000
# create a list
list1=range(size) # [0,1,2,3,4,,,,,,,,,1000000]
list2=range(size) # [0,1,2,3,4,5,,,,,1000000]
start_time=time.time()
list3=[(a+b) for a,b in zip(list1,list2)]
end_time=time.time()
print("time taken in seconds:",end_time-start_time)

time taken in seconds: 5.959591388702393


In [49]:
# numpy operation
import time
size=10000000
# create a list
arr1=np.arange(size) # [0,1,2,3,4,,,,,,,,,1000000]
arr2=np.arange(size) # [0,1,2,3,4,5,,,,,1000000]
start_time=time.time()
arr3=arr1+arr2
end_time=time.time()
print("time taken in seconds:",end_time-start_time)

time taken in seconds: 0.13601326942443848


In [7]:
import pyautogui as pg
import time 

In [8]:
print("program will run in 5sec")
time.sleep(5)
for i in range(100):
    pg.write("happy birthday happy birthday priya")
    time.sleep(0.5)
    pg.press("enter")
    

program will run in 5sec


KeyboardInterrupt: 

program will run in 5sec


KeyboardInterrupt: 

In [12]:

print("program will run in 5sec")
time.sleep(5)
for i in range(100):
    pg.write("happy birthday priya ")
    time.sleep(0.5)
    pg.press("enter")


program will run in 5sec
