In [ ]:
Write a NumPy program to replace the negative values in a NumPy array with 0.

Write a NumPy program to replace all elements of a NumPy array that are greater than the specified array.[Expected Output:
Original array:
[[ 0.42436315 0.48558583 0.32924763]
[ 0.7439979 0.58220701 0.38213418]
[ 0.5097581 0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than. 5
[[ 0.42436315 0.48558583 0.32924763]
[ 0.5 0.5 0.38213418]
[ 0.5 0.34528799 0.1563123 ]]]


Write a NumPy program to convert a NumPy array into Python list structure.


Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).


Write a NumPy program to convert 1-D arrays as columns into a 2-D array.Sample array: (10,20,30), (40,50,60)
    
Write a NumPy program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
                
                
Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.
                
Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.[Expected Output:
(3, 4, 2)
(4, 2, 3)]
                
                
Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.


Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.       
                
Write a NumPy program to multiply two given arrays of the same size element-by-element.

Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
                
Write a NumPy program to create a 3x3 identity matrix.
                
Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
                
Write a NumPy program to get help on the add function.
                

                

                

                
                
    
    
    



In [1]:
import numpy as np
arr = np.array([-1, 2, -3, 4, -5, 6, -7, 8, -9])
print("Original array:")
print(arr)
print("Replace the negative values of the said array with 0:")
arr[arr < 0] = 0
print(arr)

Original array:
[-1  2 -3  4 -5  6 -7  8 -9]
Replace the negative values of the said array with 0:
[0 2 0 4 0 6 0 8 0]


In [2]:

import numpy as np

arr = np.array([[0.42436315, 0.48558583, 0.32924763], [0.7439979, 0.58220701, 0.38213418], [0.5097581, 0.34528799, 0.1563123]])
arr[arr > 0.5] = 0.5
print(arr)

[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [3]:
import numpy as np 
a = np.array([[1,2,3], [4,5,6]]) 
print(a) 
print(a.tolist())

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [12]:
import numpy as np 
a = np.arange(11) 
np.random.shuffle(a) 
print(a)

[ 6  1  2  8  7  4  5  3  0 10  9]


In [13]:
import numpy as np
a = np.array([[10,20,30], [40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [14]:
import numpy as np

x = np.array([[0, 1, 3], [5, 7, 9]])
y = np.array([[0, 2, 4], [6, 8, 10]])

print(np.concatenate((x, y), axis=1))



[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [17]:
import numpy as np 
  
# creating a 5x5 matrix 
matrix = np.zeros((5,5), dtype = np.int) 
  
# assigning values to the matrix 
for i in range(5): 
    for j in range(5): 
        matrix[i][j] = i + j 
print (matrix)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


/var/folders/p6/z0mkbnv935lfj5knl3fvv_0m0000gp/T/ipykernel_18641/552270396.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  matrix = np.zeros((5,5), dtype = np.int)


In [18]:
import numpy as np
x = np.zeros((3,4,2))
print("Original array:")
print(x)
print("Array after modification:")
x = np.moveaxis(x, 2, 0)
print(x)

Original array:
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
Array after modification:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [19]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

y = np.array([6, 7, 8, 9, 10])

z = np.array([11, 12, 13, 14, 15])

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

print(x)

print(y)

print(z)

print(a)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
import numpy as np 
arr = np.arange(16).reshape(4, 4) 
print("Original array:") 
print(arr) 
print("New array:") 
arr = arr[:, ::-1] 
print(arr)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [21]:
import numpy as np 
  
# creating a 4x4 matrix 
matrix = np.zeros((4,4)) 
  
# replacing 0 with 1 at alternate positions 
matrix[::2, 1::2] = 1
matrix

array([[0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [22]:
import numpy as np 
  
# creating a 3X3 matrix 
X = np.eye(3) 
  
# printing the matrix 
print(X)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
import numpy as np 

array=np.zeros(10)
array1=np.ones(10)
array2=np.ones(10)*5

print(array)
print(array1)
print(array2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
impoe

In [ ]:
# Write a NumPy program to replace the negative values in a NumPy array with 0.



In [3]:
import numpy as np
arr=np.array([-1,-2,3,-4,5,6,7,-8,-9])
arr[arr<0]=0
print(arr)

[0 0 3 0 5 6 7 0 0]


In [7]:
#Write a NumPy program to replace all elements of a NumPy array that are greater than the specified array.[Expected Output:
#Original array:
#[[ 0.42436315 0.48558583 0.32924763]
#[ 0.7439979 0.58220701 0.38213418]
#[ 0.5097581 0.34528799 0.1563123 ]]
#Replace all elements of the said array with .5 which are greater than. 5
#[[ 0.42436315 0.48558583 0.32924763]
#[ 0.5 0.5 0.38213418]
#[ 0.5 0.34528799 0.1563123 ]]]


a_array=np.array([[ 0.42436315,0.48558583,0.32924763],[ 0.7439979,0.58220701,0.38213418],[ 0.5097581,0.34528799,0.1563123 ]])
a_array[a_array>0.5]=0.5
a_array


array([[0.42436315, 0.48558583, 0.32924763],
       [0.5       , 0.5       , 0.38213418],
       [0.5       , 0.34528799, 0.1563123 ]])

In [8]:
# Write a NumPy program to convert a NumPy array into Python list structure.
a=np.array([1,2,3,4,5,6,7])
b=a.tolist()
b

[1, 2, 3, 4, 5, 6, 7]

In [10]:
# Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).
import numpy as np
a=np.arange(11)
np.random.shuffle(a)
a

array([ 6,  1,  2, 10,  8,  4,  3,  9,  5,  7,  0])

In [14]:
# Write a NumPy program to convert 1-D arrays as columns into a 2-D array.Sample array: (10,20,30), (40,50,60)
one_d_array=np.array([[10,20,30],[40,50,60]])
one_d_array # 2-D array
b=np.ndarray.flatten(one_d_array) # 1-d array
b

array([10, 20, 30, 40, 50, 60])

In [18]:
#Write a NumPy program to concatenate two 2-dimensional arrays.
#Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

a=([[0, 1, 3], [5, 7, 9]]) 
b= ([[0, 2, 4], [6, 8, 10]])

np.concatenate((a,b),axis=1)
   


array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [19]:
# Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

import numpy as np 
a = np.zeros((5,5)) 
a += np.arange(5) 
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
#Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.[Expected Output:
#(3, 4, 2)
#(4, 2, 3)]
           
import numpy as np
x = np.ones((3,4,2))
x

b=np.moveaxis(x,2,0)
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [47]:
# Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.
import numpy as np
import random
a=random.randint(3,5)
a

3

In [45]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[92 15 13 91 62]
